apiVersion: v1
data:
  splunk_observability_access_token: ZFR1RkNyQ1FlS3BrLV9iVlVqNWpSUQ==
  splunk_platform_hec_token: MjM5YTA3YWUtZGEyZS00OTIzLTg2OGEtMDdlYjY5NTI3MzNk
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: splunk-otel-collector
    meta.helm.sh/release-namespace: splunk-otel-collector
  creationTimestamp: "2025-03-31T12:20:41Z"
  labels:
    app: splunk-otel-collector
    app.kubernetes.io/instance: splunk-otel-collector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: splunk-otel-collector
    app.kubernetes.io/version: 0.121.0
    chart: splunk-otel-collector-0.121.0
    helm.sh/chart: splunk-otel-collector-0.121.0
    heritage: Helm
    release: splunk-otel-collector
  name: splunk-otel-collector
  namespace: splunk-otel-collector
  resourceVersion: "6301990"
  uid: 9d9ec7fa-1941-4da2-b0da-b158ae4374a0
type: Opaque
